# Generated by Django 5.1.7 on 2025-03-23 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='Disconnected', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OcppApp.charger')),
            ],
        ),
    ]
